INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Erin","Alden","erin@gmail.com","FER76FGW6FI",1),
  ("Cameran","Sylvester","cameran@gmail.com","URU81JCZ7RH",1),
  ("Alea","Ralph","alea6174@gmail.com","SRC04FHL1DL",1),
  ("Danielle","William","danielle@gmail.com","KBK46SGZ0IM",1),
  ("Velma","Tanek","velma@gmail.com","AWR22ABC5IC",1),
  ("Sharon","Nigel","sharon3479@gmail.com","RIJ84PTD3PJ",1),
  ("Jerry","Fuller","jerry2317@gmail.com","HVN48WMA1RP",1),
  ("Tyrone","Timon","tyrone5513@gmail.com","XEF44KQE2JS",1),
  ("Lance","Quinn","lance@gmail.com","QDL88PBR1MU",1),
  ("Shaeleigh","Gil","shaeleigh@gmail.com","FLT40KVE1AB",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Ivana","Aaron","ivana@gmail.com","ETY52BBP4VX",1),
  ("Hope","Branden","hope@gmail.com","BGW37OUC7RD",1),
  ("Michael","Neville","michael190@gmail.com","JFC45UQB3HE",1),
  ("Allen","Barclay","allen5411@gmail.com","DWE32SQQ3XP",1),
  ("Neil","Hyatt","neil9845@gmail.com","KQB02RCY2DG",1),
  ("Solomon","Ashton","solomon2822@gmail.com","QFU24LBM5YQ",1),
  ("Noble","Harlan","noble6939@gmail.com","IWE33HNG4BU",1),
  ("Ulysses","Alan","ulysses6129@gmail.com","WIL36KCZ1MB",1),
  ("Ian","Bradley","ian6769@gmail.com","RJS47KFP5DP",1),
  ("Vielka","Josiah","vielka3732@gmail.com","VTO88MNU3WE",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Steel","Chaim","steel7093@gmail.com","XPL87ICO1SH",1),
  ("Ignatius","Elton","ignatius@gmail.com","RRL40EVN3OC",1),
  ("Zachery","Jelani","zachery@gmail.com","EPK94KDO1FJ",1),
  ("Evangeline","Seth","evangeline3831@gmail.com","RNL71FFF3WW",1),
  ("Callum","Kane","callum@gmail.com","ZFF87ING8FU",1),
  ("Galvin","Cedric","galvin@gmail.com","TUY42JYR4MB",1),
  ("Macey","Adam","macey3453@gmail.com","JEW43DCX2YD",1),
  ("Acton","Aidan","acton8977@gmail.com","KYF25KMG7JU",1),
  ("Gannon","Burton","gannon52@gmail.com","ZNM25ZSR9GS",1),
  ("Bert","Geoffrey","bert8804@gmail.com","LYN93EIN1AE",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Emily","Malachi","emily4701@gmail.com","FKE26WAI2UD",1),
  ("Melinda","Hayden","melinda1432@gmail.com","PKK24EEL2WE",1),
  ("Chancellor","Marsden","chancellor@gmail.com","MGR38LXF2TH",1),
  ("Teagan","Cedric","teagan@gmail.com","SCN53DDR3PU",1),
  ("Quintessa","Devin","quintessa@gmail.com","BGL62ZJJ5FY",1),
  ("Scarlet","Aidan","scarlet@gmail.com","YWS98OFJ7FV",1),
  ("Germane","Ross","germane@gmail.com","VKW06ABK8IZ",1),
  ("Shelly","Micah","shelly2738@gmail.com","NKG53QKQ3JY",1),
  ("Clayton","Nero","clayton@gmail.com","JHQ75UHL5JO",1),
  ("Risa","Bruno","risa@gmail.com","DEU24KOF1EV",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Guy","Quentin","guy@gmail.com","YCF71SIK2GN",1),
  ("Gisela","Stewart","gisela@gmail.com","VYE53IVK5LO",1),
  ("Nora","Wesley","nora@gmail.com","TGN10GMI2GU",1),
  ("Hedley","Ralph","hedley1292@gmail.com","UYU86NYD1SN",1),
  ("Bruno","Clinton","bruno@gmail.com","FTG53DWU9TB",1),
  ("Lysandra","Igor","lysandra6791@gmail.com","XLO85VCB6PJ",1),
  ("Marny","Orson","marny1063@gmail.com","NBV38YON8FO",1),
  ("Maxwell","Amir","maxwell875@gmail.com","GBU92INV6KM",1),
  ("Chester","Eaton","chester4404@gmail.com","FYH53UMR1GI",1),
  ("Helen","Maxwell","helen7613@gmail.com","XYO72KSD2BT",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Hiram","Dean","hiram4330@gmail.com","LZZ92CDB7TO",1),
  ("Harding","Camden","harding1019@gmail.com","AER67HYI4AX",1),
  ("Allistair","Kevin","allistair@gmail.com","EGG27PVV6MP",1),
  ("Maya","Herrod","maya@gmail.com","VXD71XVS3KA",1),
  ("Zane","Thane","zane@gmail.com","MGT74XXE7QQ",1),
  ("Levi","Ahmed","levi@gmail.com","CKD64LCG2SU",1),
  ("Alvin","Reese","alvin@gmail.com","OLR83WWK4RL",1),
  ("Grady","Knox","grady3483@gmail.com","UBB33VTO4FC",1),
  ("Kai","John","kai@gmail.com","RGX60DLX6WU",1),
  ("Simone","Devin","simone@gmail.com","TPQ39TRH5QF",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Neville","Tyler","neville932@gmail.com","BPP02GLB0DF",1),
  ("Owen","Eagan","owen1106@gmail.com","AXB95YXJ7WV",1),
  ("Erasmus","Gray","erasmus@gmail.com","URY50XEJ9MQ",1),
  ("Nevada","Reese","nevada@gmail.com","DPJ22HYO2OF",1),
  ("Cora","Victor","cora@gmail.com","MDI84XBH3VJ",1),
  ("Ethan","Guy","ethan2614@gmail.com","UNA45KPK8VP",1),
  ("Doris","Elton","doris@gmail.com","EXJ13AHR6PB",1),
  ("Karleigh","Cooper","karleigh@gmail.com","UWO06UTW6KO",1),
  ("Julian","Alden","julian5249@gmail.com","WTJ94CLQ8WU",1),
  ("Selma","Rooney","selma@gmail.com","YTM45MIN8QG",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Raymond","Alvin","raymond@gmail.com","TXO94LOU1EG",1),
  ("Chaim","Levi","chaim@gmail.com","GAI74CUH2MC",1),
  ("Ina","Stone","ina@gmail.com","VYC77MLA0TL",1),
  ("Quynn","Marsden","quynn976@gmail.com","DRD85BSY3QY",1),
  ("Eric","Giacomo","eric@gmail.com","CCF47LKK9KN",1),
  ("Amery","Craig","amery@gmail.com","HKX11TUQ9RG",1),
  ("Erin","Colby","erin@gmail.com","WJG50FNE1EM",1),
  ("Addison","Len","addison@gmail.com","PAO66MXO7HE",1),
  ("Hamilton","Nero","hamilton@gmail.com","LIM15CHL1TP",1),
  ("Prescott","Malachi","prescott@gmail.com","YDA79VTK2DC",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Sigourney","Slade","sigourney@gmail.com","UZY62RCA1PT",1),
  ("Dexter","Benedict","dexter@gmail.com","PNI64ENP6GQ",1),
  ("Lysandra","Dexter","lysandra7396@gmail.com","RNT00XDP7MN",1),
  ("Susan","Forrest","susan@gmail.com","DCT61BED1TE",1),
  ("Hop","Erasmus","hop@gmail.com","FVA35HUB6SR",1),
  ("Nathan","Rudyard","nathan@gmail.com","ZJL45XTN2MV",1),
  ("Quynn","Francis","quynn4684@gmail.com","QOX61DPA4XY",1),
  ("Hyacinth","Gregory","hyacinth3154@gmail.com","LYP59XNU9ME",1),
  ("Rana","Anthony","rana@gmail.com","LKL31KXP3HV",1),
  ("Rinah","Keith","rinah351@gmail.com","EVK54OOI8NL",1);
INSERT INTO `accounts` (`first_name`,`last_name`,`email`,`password`,`type`)
VALUES
  ("Nora","Travis","nora7840@gmail.com","TKY97MQL5FQ",1),
  ("Colorado","Blaze","colorado5149@gmail.com","QOK67JKF0NR",1),
  ("Jillian","Nicholas","jillian8004@gmail.com","TMO94MVR5VU",1),
  ("Joel","Fritz","joel@gmail.com","HOZ38NUF3YM",1),
  ("Isadora","Quinn","isadora@gmail.com","WON92UGW2FL",1),
  ("Aidan","Aaron","aidan6413@gmail.com","NRG41WBN0WP",1),
  ("Elliott","Alan","elliott@gmail.com","CYV56QQP1OB",1),
  ("Ferris","Stuart","ferris9700@gmail.com","FFE77HMK9VT",1),
  ("Beck","Ciaran","beck148@gmail.com","DLR27DBE9CM",1),
  ("Britanney","Cain","britanney1456@gmail.com","PBK54AOV9RK",1);
